wordpressUsername: user
wordpressPassword: "password"

service:
    type: ClusterIP

ingress:
    enabled: true
    pathType: ImplementationSpecific
    ingressClassName: nginx
    hostname: sunday-workspace-wordpress.aiscaler.ai
    path: /
    annotations:
        external-dns.alpha.kubernetes.io/hostname: sunday-workspace-wordpress.aiscaler.ai
        cert-manager.io/cluster-issuer: letsencrypt-prod
    tls: true