export const countries = [
  {
    name: "Algeria",
    dialCode: "+213",
    code: "DZ",
    flag: "https://flagcdn.com/dz.svg",
    limitNumber: 9,
    example: "+213 551 234 567",
  },
  {
    name: "Angola",
    dialCode: "+244",
    code: "AO",
    flag: "https://flagcdn.com/ao.svg",
    limitNumber: 9,
    example: "+244 923 456 789",
  },
  {
    name: "Benin",
    dialCode: "+229",
    code: "BJ",
    flag: "https://flagcdn.com/bj.svg",
    limitNumber: 8,
    example: "+229 90 12 34 56",
  },
  {
    name: "Botswana",
    dialCode: "+267",
    code: "BW",
    flag: "https://flagcdn.com/bw.svg",
    limitNumber: 8,
    example: "+267 71 234 567",
  },
  {
    name: "Burkina Faso",
    dialCode: "+226",
    code: "BF",
    flag: "https://flagcdn.com/bf.svg",
    limitNumber: 8,
    example: "+226 70 12 34 56",
  },
  {
    name: "Burundi",
    dialCode: "+257",
    code: "BI",
    flag: "https://flagcdn.com/bi.svg",
    limitNumber: 8,
    example: "+257 79 12 34 56",
  },
  {
    name: "Cabo Verde",
    dialCode: "+238",
    code: "CV",
    flag: "https://flagcdn.com/cv.svg",
    limitNumber: 7,
    example: "+238 912 34 56",
  },
  {
    name: "Cameroon",
    dialCode: "+237",
    code: "CM",
    flag: "https://flagcdn.com/cm.svg",
    limitNumber: 9,
    example: "+237 691 234 567",
  },
  {
    name: "Central African Republic",
    dialCode: "+236",
    code: "CF",
    flag: "https://flagcdn.com/cf.svg",
    limitNumber: 8,
    example: "+236 72 12 34 56",
  },
  {
    name: "Chad",
    dialCode: "+235",
    code: "TD",
    flag: "https://flagcdn.com/td.svg",
    limitNumber: 8,
    example: "+235 63 12 34 56",
  },
  {
    name: "Comoros",
    dialCode: "+269",
    code: "KM",
    flag: "https://flagcdn.com/km.svg",
    limitNumber: 7,
    example: "+269 771 23 45",
  },
  {
    name: "Congo",
    dialCode: "+242",
    code: "CG",
    flag: "https://flagcdn.com/cg.svg",
    limitNumber: 9,
    example: "+242 06 123 4567",
  },
  {
    name: "Congo, Democratic Republic of the",
    dialCode: "+243",
    code: "CD",
    flag: "https://flagcdn.com/cd.svg",
    limitNumber: 9,
    example: "+243 81 234 5678",
  },
  {
    name: "Côte d'Ivoire",
    dialCode: "+225",
    code: "CI",
    flag: "https://flagcdn.com/ci.svg",
    limitNumber: 10,
    example: "+225 07 12 345 678",
  },
  {
    name: "Djibouti",
    dialCode: "+253",
    code: "DJ",
    flag: "https://flagcdn.com/dj.svg",
    limitNumber: 8,
    example: "+253 77 12 34 56",
  },
  {
    name: "Egypt",
    dialCode: "+20",
    code: "EG",
    flag: "https://flagcdn.com/eg.svg",
    limitNumber: 10,
    example: "+20 100 123 4567",
  },
  {
    name: "Equatorial Guinea",
    dialCode: "+240",
    code: "GQ",
    flag: "https://flagcdn.com/gq.svg",
    limitNumber: 9,
    example: "+240 222 123 456",
  },
  {
    name: "Eritrea",
    dialCode: "+291",
    code: "ER",
    flag: "https://flagcdn.com/er.svg",
    limitNumber: 7,
    example: "+291 7 123 456",
  },
  {
    name: "Eswatini",
    dialCode: "+268",
    code: "SZ",
    flag: "https://flagcdn.com/sz.svg",
    limitNumber: 8,
    example: "+268 76 12 34 56",
  },
  {
    name: "Ethiopia",
    dialCode: "+251",
    code: "ET",
    flag: "https://flagcdn.com/et.svg",
    limitNumber: 9,
    example: "+251 91 123 4567",
  },
  {
    name: "Gabon",
    dialCode: "+241",
    code: "GA",
    flag: "https://flagcdn.com/ga.svg",
    limitNumber: 8,
    example: "+241 07 12 34 56",
  },
  {
    name: "Gambia",
    dialCode: "+220",
    code: "GM",
    flag: "https://flagcdn.com/gm.svg",
    limitNumber: 7,
    example: "+220 312 3456",
  },
  {
    name: "Ghana",
    dialCode: "+233",
    code: "GH",
    flag: "https://flagcdn.com/gh.svg",
    limitNumber: 9,
    example: "+233 24 456 7890",
  },
  {
    name: "Guinea",
    dialCode: "+224",
    code: "GN",
    flag: "https://flagcdn.com/gn.svg",
    limitNumber: 9,
    example: "+224 621 23 45 67",
  },
  {
    name: "Guinea-Bissau",
    dialCode: "+245",
    code: "GW",
    flag: "https://flagcdn.com/gw.svg",
    limitNumber: 7,
    example: "+245 955 123 456",
  },
  {
    name: "Kenya",
    dialCode: "+254",
    code: "KE",
    flag: "https://flagcdn.com/ke.svg",
    limitNumber: 9,
    example: "+254 712 345 678",
  },
  {
    name: "Lesotho",
    dialCode: "+266",
    code: "LS",
    flag: "https://flagcdn.com/ls.svg",
    limitNumber: 8,
    example: "+266 5012 3456",
  },
  {
    name: "Liberia",
    dialCode: "+231",
    code: "LR",
    flag: "https://flagcdn.com/lr.svg",
    limitNumber: 9,
    example: "+231 77 012 3456",
  },
  {
    name: "Libya",
    dialCode: "+218",
    code: "LY",
    flag: "https://flagcdn.com/ly.svg",
    limitNumber: 9,
    example: "+218 91 234 5678",
  },
  {
    name: "Madagascar",
    dialCode: "+261",
    code: "MG",
    flag: "https://flagcdn.com/mg.svg",
    limitNumber: 9,
    example: "+261 34 12 345 67",
  },
  {
    name: "Malawi",
    dialCode: "+265",
    code: "MW",
    flag: "https://flagcdn.com/mw.svg",
    limitNumber: 9,
    example: "+265 99 123 4567",
  },
  {
    name: "Mali",
    dialCode: "+223",
    code: "ML",
    flag: "https://flagcdn.com/ml.svg",
    limitNumber: 8,
    example: "+223 71 23 45 67",
  },
  {
    name: "Mauritania",
    dialCode: "+222",
    code: "MR",
    flag: "https://flagcdn.com/mr.svg",
    limitNumber: 8,
    example: "+222 36 12 34 56",
  },
  {
    name: "Mauritius",
    dialCode: "+230",
    code: "MU",
    flag: "https://flagcdn.com/mu.svg",
    limitNumber: 8,
    example: "+230 5123 4567",
  },
  {
    name: "Morocco",
    dialCode: "+212",
    code: "MA",
    flag: "https://flagcdn.com/ma.svg",
    limitNumber: 9,
    example: "+212 661 234 567",
  },
  {
    name: "Mozambique",
    dialCode: "+258",
    code: "MZ",
    flag: "https://flagcdn.com/mz.svg",
    limitNumber: 9,
    example: "+258 84 123 4567",
  },
  {
    name: "Namibia",
    dialCode: "+264",
    code: "NA",
    flag: "https://flagcdn.com/na.svg",
    limitNumber: 9,
    example: "+264 81 234 5678",
  },
  {
    name: "Niger",
    dialCode: "+227",
    code: "NE",
    flag: "https://flagcdn.com/ne.svg",
    limitNumber: 8,
    example: "+227 91 23 45 67",
  },
  {
    name: "Nigeria",
    dialCode: "+234",
    code: "NG",
    flag: "https://flagcdn.com/ng.svg",
    limitNumber: 10,
    example: "+234 812 345 6789",
  },
  {
    name: "Rwanda",
    dialCode: "+250",
    code: "RW",
    flag: "https://flagcdn.com/rw.svg",
    limitNumber: 9,
    example: "+250 781 234 567",
  },
  {
    name: "Sao Tome and Principe",
    dialCode: "+239",
    code: "ST",
    flag: "https://flagcdn.com/st.svg",
    limitNumber: 7,
    example: "+239 991 2345",
  },
  {
    name: "Senegal",
    dialCode: "+221",
    code: "SN",
    flag: "https://flagcdn.com/sn.svg",
    limitNumber: 9,
    example: "+221 77 123 4567",
  },
  {
    name: "Seychelles",
    dialCode: "+248",
    code: "SC",
    flag: "https://flagcdn.com/sc.svg",
    limitNumber: 7,
    example: "+248 2 123 456",
  },
  {
    name: "Sierra Leone",
    dialCode: "+232",
    code: "SL",
    flag: "https://flagcdn.com/sl.svg",
    limitNumber: 8,
    example: "+232 76 123 456",
  },
  {
    name: "Somalia",
    dialCode: "+252",
    code: "SO",
    flag: "https://flagcdn.com/so.svg",
    limitNumber: 9,
    example: "+252 61 234 5678",
  },
  {
    name: "South Africa",
    dialCode: "+27",
    code: "ZA",
    flag: "https://flagcdn.com/za.svg",
    limitNumber: 9,
    example: "+27 83 123 4567",
  },
  {
    name: "South Sudan",
    dialCode: "+211",
    code: "SS",
    flag: "https://flagcdn.com/ss.svg",
    limitNumber: 9,
    example: "+211 92 123 4567",
  },
  {
    name: "Sudan",
    dialCode: "+249",
    code: "SD",
    flag: "https://flagcdn.com/sd.svg",
    limitNumber: 9,
    example: "+249 91 234 5678",
  },
  {
    name: "Togo",
    dialCode: "+228",
    code: "TG",
    flag: "https://flagcdn.com/tg.svg",
    limitNumber: 8,
    example: "+228 90 12 34 56",
  },
  {
    name: "Tunisia",
    dialCode: "+216",
    code: "TN",
    flag: "https://flagcdn.com/tn.svg",
    limitNumber: 8,
    example: "+216 98 123 456",
  },
  {
    name: "Uganda",
    dialCode: "+256",
    code: "UG",
    flag: "https://flagcdn.com/ug.svg",
    limitNumber: 9,
    example: "+256 701 234 567",
  },
  {
    name: "Zambia",
    dialCode: "+260",
    code: "ZM",
    flag: "https://flagcdn.com/zm.svg",
    limitNumber: 9,
    example: "+260 96 123 4567",
  },
  {
    name: "Zimbabwe",
    dialCode: "+263",
    code: "ZW",
    flag: "https://flagcdn.com/zw.svg",
    limitNumber: 9,
    example: "+263 77 123 4567",
  },
  // Rest of the World (141 countries, alphabetically ordered)
  {
    name: "Afghanistan",
    dialCode: "+93",
    code: "AF",
    flag: "https://flagcdn.com/af.svg",
    limitNumber: 9,
    example: "+93 70 123 4567",
  },
  {
    name: "Albania",
    dialCode: "+355",
    code: "AL",
    flag: "https://flagcdn.com/al.svg",
    limitNumber: 9,
    example: "+355 69 123 4567",
  },
  {
    name: "Andorra",
    dialCode: "+376",
    code: "AD",
    flag: "https://flagcdn.com/ad.svg",
    limitNumber: 6,
    example: "+376 123 456",
  },
  {
    name: "Antigua and Barbuda",
    dialCode: "+1",
    code: "268",
    flag: "https://flagcdn.com/ag.svg",
    limitNumber: 10,
    example: "+1 268 0 123 4567",
  },
  {
    name: "Argentina",
    dialCode: "+54",
    code: "AR",
    flag: "https://flagcdn.com/ar.svg",
    limitNumber: 10,
    example: "+54 11 1234 5678",
  },
  {
    name: "Armenia",
    dialCode: "+374",
    code: "AM",
    flag: "https://flagcdn.com/am.svg",
    limitNumber: 8,
    example: "+374 91 234 567",
  },
  {
    name: "Australia",
    dialCode: "+61",
    code: "AU",
    flag: "https://flagcdn.com/au.svg",
    limitNumber: 9,
    example: "+61 412 345 678",
  },
  {
    name: "Austria",
    dialCode: "+43",
    code: "AT",
    flag: "https://flagcdn.com/at.svg",
    limitNumber: 10,
    example: "+43 664 123 4567",
  },
  {
    name: "Azerbaijan",
    dialCode: "+994",
    code: "AZ",
    flag: "https://flagcdn.com/az.svg",
    limitNumber: 9,
    example: "+994 50 123 4567",
  },
  {
    name: "Bahamas",
    dialCode: "+1",
    code: "124",
    flag: "https://flagcdn.com/bs.svg",
    limitNumber: 10,
    example: "+1242 012 3456",
  },
  {
    name: "Bahrain",
    dialCode: "+973",
    code: "BH",
    flag: "https://flagcdn.com/bh.svg",
    limitNumber: 8,
    example: "+973 1234 5678",
  },
  {
    name: "Bangladesh",
    dialCode: "+880",
    code: "BD",
    flag: "https://flagcdn.com/bd.svg",
    limitNumber: 10,
    example: "+880 1812 345678",
  },
  {
    name: "Barbados",
    dialCode: "+1",
    code: "246",
    flag: "https://flagcdn.com/bb.svg",
    limitNumber: 10,
    example: " +1 246 012 3456",
  },
  {
    name: "Belgium",
    dialCode: "+32",
    code: "BE",
    flag: "https://flagcdn.com/be.svg",
    limitNumber: 9,
    example: "+32 471 234 567",
  },
  {
    name: "Belize",
    dialCode: "+501",
    code: "BZ",
    flag: "https://flagcdn.com/bz.svg",
    limitNumber: 7,
    example: "+501 612 3456",
  },
  {
    name: "Bhutan",
    dialCode: "+975",
    code: "BT",
    flag: "https://flagcdn.com/bt.svg",
    limitNumber: 8,
    example: "+975 17 123 456",
  },
  {
    name: "Bolivia",
    dialCode: "+591",
    code: "BO",
    flag: "https://flagcdn.com/bo.svg",
    limitNumber: 8,
    example: "+591 7 123 4567",
  },
  {
    name: "Bosnia and Herzegovina",
    dialCode: "+387",
    code: "BA",
    flag: "https://flagcdn.com/ba.svg",
    limitNumber: 8,
    example: "+387 61 234 567",
  },
  {
    name: "Brazil",
    dialCode: "+55",
    code: "BR",
    flag: "https://flagcdn.com/br.svg",
    limitNumber: 11,
    example: "+55 11 98765 4321",
  },
  {
    name: "Brunei",
    dialCode: "+673",
    code: "BN",
    flag: "https://flagcdn.com/bn.svg",
    limitNumber: 7,
    example: "+673 123 4567",
  },
  {
    name: "Bulgaria",
    dialCode: "+359",
    code: "BG",
    flag: "https://flagcdn.com/bg.svg",
    limitNumber: 9,
    example: "+359 88 123 4567",
  },
  {
    name: "Cambodia",
    dialCode: "+855",
    code: "KH",
    flag: "https://flagcdn.com/kh.svg",
    limitNumber: 9,
    example: "+855 91 234 567",
  },
  {
    name: "Canada",
    dialCode: "+1",
    code: "CA",
    flag: "https://flagcdn.com/ca.svg",
    limitNumber: 10,
    example: "+1 (416) 123 4567",
  },
  {
    name: "Chile",
    dialCode: "+56",
    code: "CL",
    flag: "https://flagcdn.com/cl.svg",
    limitNumber: 9,
    example: "+56 9 1234 5678",
  },
  {
    name: "China",
    dialCode: "+86",
    code: "CN",
    flag: "https://flagcdn.com/cn.svg",
    limitNumber: 11,
    example: "+86 138 1234 5678",
  },
  {
    name: "Colombia",
    dialCode: "+57",
    code: "CO",
    flag: "https://flagcdn.com/co.svg",
    limitNumber: 10,
    example: "+57 300 1234567",
  },
  {
    name: "Costa Rica",
    dialCode: "+506",
    code: "CR",
    flag: "https://flagcdn.com/cr.svg",
    limitNumber: 8,
    example: "+506 1234 5678",
  },
  {
    name: "Croatia",
    dialCode: "+385",
    code: "HR",
    flag: "https://flagcdn.com/hr.svg",
    limitNumber: 9,
    example: "+385 91 234 5678",
  },
  {
    name: "Cuba",
    dialCode: "+53",
    code: "CU",
    flag: "https://flagcdn.com/cu.svg",
    limitNumber: 8,
    example: "+53 5 1234567",
  },
  {
    name: "Cyprus",
    dialCode: "+357",
    code: "CY",
    flag: "https://flagcdn.com/cy.svg",
    limitNumber: 8,
    example: "+357 99 123 456",
  },
  {
    name: "Czech Republic",
    dialCode: "+420",
    code: "CZ",
    flag: "https://flagcdn.com/cz.svg",
    limitNumber: 9,
    example: "+420 123 456 789",
  },
  {
    name: "Denmark",
    dialCode: "+45",
    code: "DK",
    flag: "https://flagcdn.com/dk.svg",
    limitNumber: 8,
    example: "+45 12 34 56 78",
  },
  {
    name: "Dominica",
    dialCode: "+1",
    code: "767",
    flag: "https://flagcdn.com/dm.svg",
    limitNumber: 10,
    example: "+1 767 012 3456",
  },
  {
    name: "Dominican Republic",
    dialCode: "+1",
    code: "809",
    flag: "https://flagcdn.com/do.svg",
    limitNumber: 10,
    example: "+1 809 012 3456",
  },
  {
    name: "Ecuador",
    dialCode: "+593",
    code: "EC",
    flag: "https://flagcdn.com/ec.svg",
    limitNumber: 9,
    example: "+593 99 123 4567",
  },
  {
    name: "El Salvador",
    dialCode: "+503",
    code: "SV",
    flag: "https://flagcdn.com/sv.svg",
    limitNumber: 8,
    example: "+503 1234 5678",
  },
  {
    name: "Estonia",
    dialCode: "+372",
    code: "EE",
    flag: "https://flagcdn.com/ee.svg",
    limitNumber: 8,
    example: "+372 1234 5678",
  },
  {
    name: "Fiji",
    dialCode: "+679",
    code: "FJ",
    flag: "https://flagcdn.com/fj.svg",
    limitNumber: 7,
    example: "+679 123 4567",
  },
  {
    name: "Finland",
    dialCode: "+358",
    code: "FI",
    flag: "https://flagcdn.com/fi.svg",
    limitNumber: 9,
    example: "+358 40 123 4567",
  },
  {
    name: "France",
    dialCode: "+33",
    code: "FR",
    flag: "https://flagcdn.com/fr.svg",
    limitNumber: 9,
    example: "+33 6 12 34 56 78",
  },
  {
    name: "Georgia",
    dialCode: "+995",
    code: "GE",
    flag: "https://flagcdn.com/ge.svg",
    limitNumber: 9,
    example: "+995 551 234 567",
  },
  {
    name: "Germany",
    dialCode: "+49",
    code: "DE",
    flag: "https://flagcdn.com/de.svg",
    limitNumber: 11,
    example: "+49 176 1234 5678",
  },
  {
    name: "Greece",
    dialCode: "+30",
    code: "GR",
    flag: "https://flagcdn.com/gr.svg",
    limitNumber: 10,
    example: "+30 691 234 5678",
  },
  {
    name: "Grenada",
    dialCode: "+1",
    code: "473",
    flag: "https://flagcdn.com/gd.svg",
    limitNumber: 10,
    example: "+1 473 012 3456",
  },
  {
    name: "Guatemala",
    dialCode: "+502",
    code: "GT",
    flag: "https://flagcdn.com/gt.svg",
    limitNumber: 8,
    example: "+502 1234 5678",
  },
  {
    name: "Guyana",
    dialCode: "+592",
    code: "GY",
    flag: "https://flagcdn.com/gy.svg",
    limitNumber: 7,
    example: "+592 123 4567",
  },
  {
    name: "Haiti",
    dialCode: "+509",
    code: "HT",
    flag: "https://flagcdn.com/ht.svg",
    limitNumber: 8,
    example: "+509 34 12 34 56",
  },
  {
    name: "Honduras",
    dialCode: "+504",
    code: "HN",
    flag: "https://flagcdn.com/hn.svg",
    limitNumber: 8,
    example: "+504 1234 5678",
  },
  {
    name: "Hungary",
    dialCode: "+36",
    code: "HU",
    flag: "https://flagcdn.com/hu.svg",
    limitNumber: 9,
    example: "+36 30 123 4567",
  },
  {
    name: "Iceland",
    dialCode: "+354",
    code: "IS",
    flag: "https://flagcdn.com/is.svg",
    limitNumber: 7,
    example: "+354 123 4567",
  },
  {
    name: "India",
    dialCode: "+91",
    code: "IN",
    flag: "https://flagcdn.com/in.svg",
    limitNumber: 10,
    example: "+91 98765 43210",
  },
  {
    name: "Indonesia",
    dialCode: "+62",
    code: "ID",
    flag: "https://flagcdn.com/id.svg",
    limitNumber: 10,
    example: "+62 812 3456 7890",
  },
  {
    name: "Iran",
    dialCode: "+98",
    code: "IR",
    flag: "https://flagcdn.com/ir.svg",
    limitNumber: 10,
    example: "+98 912 345 6789",
  },
  {
    name: "Iraq",
    dialCode: "+964",
    code: "IQ",
    flag: "https://flagcdn.com/iq.svg",
    limitNumber: 10,
    example: "+964 771 234 5678",
  },
  {
    name: "Ireland",
    dialCode: "+353",
    code: "IE",
    flag: "https://flagcdn.com/ie.svg",
    limitNumber: 9,
    example: "+353 87 123 4567",
  },
  {
    name: "Israel",
    dialCode: "+972",
    code: "IL",
    flag: "https://flagcdn.com/il.svg",
    limitNumber: 9,
    example: "+972 54 123 4567",
  },
  {
    name: "Italy",
    dialCode: "+39",
    code: "IT",
    flag: "https://flagcdn.com/it.svg",
    limitNumber: 10,
    example: "+39 345 678 9012",
  },
  {
    name: "Jamaica",
    dialCode: "+1",
    code: "876",
    flag: "https://flagcdn.com/jm.svg",
    limitNumber: 10,
    example: "+1 876 012 3456",
  },
  {
    name: "Japan",
    dialCode: "+81",
    code: "JP",
    flag: "https://flagcdn.com/jp.svg",
    limitNumber: 10,
    example: "+81 90 1234 5678",
  },
  {
    name: "Jordan",
    dialCode: "+962",
    code: "JO",
    flag: "https://flagcdn.com/jo.svg",
    limitNumber: 9,
    example: "+962 7 9123 4567",
  },
  {
    name: "Kazakhstan",
    dialCode: "+7",
    code: "KZ",
    flag: "https://flagcdn.com/kz.svg",
    limitNumber: 10,
    example: "+7 701 234 5678",
  },
  {
    name: "Kuwait",
    dialCode: "+965",
    code: "KW",
    flag: "https://flagcdn.com/kw.svg",
    limitNumber: 8,
    example: "+965 1234 5678",
  },
  {
    name: "Kyrgyzstan",
    dialCode: "+996",
    code: "KG",
    flag: "https://flagcdn.com/kg.svg",
    limitNumber: 9,
    example: "+996 555 123 456",
  },
  {
    name: "Laos",
    dialCode: "+856",
    code: "LA",
    flag: "https://flagcdn.com/la.svg",
    limitNumber: 8,
    example: "+856 20 1234 5678",
  },
  {
    name: "Latvia",
    dialCode: "+371",
    code: "LV",
    flag: "https://flagcdn.com/lv.svg",
    limitNumber: 8,
    example: "+371 1234 5678",
  },
  {
    name: "Lebanon",
    dialCode: "+961",
    code: "LB",
    flag: "https://flagcdn.com/lb.svg",
    limitNumber: 8,
    example: "+961 3 123 456",
  },
  {
    name: "Liechtenstein",
    dialCode: "+423",
    code: "LI",
    flag: "https://flagcdn.com/li.svg",
    limitNumber: 7,
    example: "+423 123 4567",
  },
  {
    name: "Lithuania",
    dialCode: "+370",
    code: "LT",
    flag: "https://flagcdn.com/lt.svg",
    limitNumber: 8,
    example: "+370 612 34567",
  },
  {
    name: "Luxembourg",
    dialCode: "+352",
    code: "LU",
    flag: "https://flagcdn.com/lu.svg",
    limitNumber: 9,
    example: "+352 691 234 567",
  },
  {
    name: "Malaysia",
    dialCode: "+60",
    code: "MY",
    flag: "https://flagcdn.com/my.svg",
    limitNumber: 9,
    example: "+60 12 345 6789",
  },
  {
    name: "Maldives",
    dialCode: "+960",
    code: "MV",
    flag: "https://flagcdn.com/mv.svg",
    limitNumber: 7,
    example: "+960 123 4567",
  },
  {
    name: "Malta",
    dialCode: "+356",
    code: "MT",
    flag: "https://flagcdn.com/mt.svg",
    limitNumber: 8,
    example: "+356 1234 5678",
  },
  {
    name: "Mexico",
    dialCode: "+52",
    code: "MX",
    flag: "https://flagcdn.com/mx.svg",
    limitNumber: 10,
    example: "+52 55 1234 5678",
  },
  {
    name: "Moldova",
    dialCode: "+373",
    code: "MD",
    flag: "https://flagcdn.com/md.svg",
    limitNumber: 8,
    example: "+373 691 234 56",
  },
  {
    name: "Monaco",
    dialCode: "+377",
    code: "MC",
    flag: "https://flagcdn.com/mc.svg",
    limitNumber: 8,
    example: "+377 12 34 56 78",
  },
  {
    name: "Mongolia",
    dialCode: "+976",
    code: "MN",
    flag: "https://flagcdn.com/mn.svg",
    limitNumber: 8,
    example: "+976 9912 3456",
  },
  {
    name: "Montenegro",
    dialCode: "+382",
    code: "ME",
    flag: "https://flagcdn.com/me.svg",
    limitNumber: 8,
    example: "+382 67 123 456",
  },
  {
    name: "Myanmar",
    dialCode: "+95",
    code: "MM",
    flag: "https://flagcdn.com/mm.svg",
    limitNumber: 9,
    example: "+95 9 123 456 789",
  },
  {
    name: "Nepal",
    dialCode: "+977",
    code: "NP",
    flag: "https://flagcdn.com/np.svg",
    limitNumber: 10,
    example: "+977 984 123 4567",
  },
  {
    name: "Netherlands",
    dialCode: "+31",
    code: "NL",
    flag: "https://flagcdn.com/nl.svg",
    limitNumber: 9,
    example: "+31 6 12345678",
  },
  {
    name: "New Zealand",
    dialCode: "+64",
    code: "NZ",
    flag: "https://flagcdn.com/nz.svg",
    limitNumber: 9,
    example: "+64 21 123 4567",
  },
  {
    name: "Nicaragua",
    dialCode: "+505",
    code: "NI",
    flag: "https://flagcdn.com/ni.svg",
    limitNumber: 8,
    example: "+505 1234 5678",
  },
  {
    name: "North Korea",
    dialCode: "+850",
    code: "KP",
    flag: "https://flagcdn.com/kp.svg",
    limitNumber: 8,
    example: "+850 191 123 4567",
  },
  {
    name: "North Macedonia",
    dialCode: "+389",
    code: "MK",
    flag: "https://flagcdn.com/mk.svg",
    limitNumber: 8,
    example: "+389 70 123 456",
  },
  {
    name: "Norway",
    dialCode: "+47",
    code: "NO",
    flag: "https://flagcdn.com/no.svg",
    limitNumber: 8,
    example: "+47 912 34 567",
  },
  {
    name: "Oman",
    dialCode: "+968",
    code: "OM",
    flag: "https://flagcdn.com/om.svg",
    limitNumber: 8,
    example: "+968 9123 4567",
  },
  {
    name: "Pakistan",
    dialCode: "+92",
    code: "PK",
    flag: "https://flagcdn.com/pk.svg",
    limitNumber: 10,
    example: "+92 300 1234567",
  },
  {
    name: "Panama",
    dialCode: "+507",
    code: "PA",
    flag: "https://flagcdn.com/pa.svg",
    limitNumber: 8,
    example: "+507 1234 5678",
  },
  {
    name: "Papua New Guinea",
    dialCode: "+675",
    code: "PG",
    flag: "https://flagcdn.com/pg.svg",
    limitNumber: 8,
    example: "+675 712 34567",
  },
  {
    name: "Paraguay",
    dialCode: "+595",
    code: "PY",
    flag: "https://flagcdn.com/py.svg",
    limitNumber: 9,
    example: "+595 981 234 567",
  },
  {
    name: "Peru",
    dialCode: "+51",
    code: "PE",
    flag: "https://flagcdn.com/pe.svg",
    limitNumber: 9,
    example: "+51 912 345 678",
  },
  {
    name: "Philippines",
    dialCode: "+63",
    code: "PH",
    flag: "https://flagcdn.com/ph.svg",
    limitNumber: 10,
    example: "+63 917 123 4567",
  },
  {
    name: "Poland",
    dialCode: "+48",
    code: "PL",
    flag: "https://flagcdn.com/pl.svg",
    limitNumber: 9,
    example: "+48 512 345 678",
  },
  {
    name: "Portugal",
    dialCode: "+351",
    code: "PT",
    flag: "https://flagcdn.com/pt.svg",
    limitNumber: 9,
    example: "+351 912 345 678",
  },
  {
    name: "Qatar",
    dialCode: "+974",
    code: "QA",
    flag: "https://flagcdn.com/qa.svg",
    limitNumber: 8,
    example: "+974 1234 5678",
  },
  {
    name: "Russia",
    dialCode: "+7",
    code: "RU",
    flag: "https://flagcdn.com/ru.svg",
    limitNumber: 10,
    example: "+7 912 345 6789",
  },
  {
    name: "Saint Lucia",
    dialCode: "+1",
    code: "758",
    flag: "https://flagcdn.com/lc.svg",
    limitNumber: 10,
    example: "+1 758 012 3456",
  },
  {
    name: "Saint Vincent and the Grenadines",
    dialCode: "+1",
    code: "784",
    flag: "https://flagcdn.com/vc.svg",
    limitNumber: 10,
    example: "+1 784 012 3456",
  },
  {
    name: "Samoa",
    dialCode: "+685",
    code: "WS",
    flag: "https://flagcdn.com/ws.svg",
    limitNumber: 7,
    example: "+685 1234567",
  },
  {
    name: "San Marino",
    dialCode: "+378",
    code: "SM",
    flag: "https://flagcdn.com/sm.svg",
    limitNumber: 10,
    example: "+378 123 456 7890",
  },
  {
    name: "Saudi Arabia",
    dialCode: "+966",
    code: "SA",
    flag: "https://flagcdn.com/sa.svg",
    limitNumber: 9,
    example: "+966 50 123 4567",
  },
  {
    name: "Serbia",
    dialCode: "+381",
    code: "RS",
    flag: "https://flagcdn.com/rs.svg",
    limitNumber: 9,
    example: "+381 60 123 4567",
  },
  {
    name: "Singapore",
    dialCode: "+65",
    code: "SG",
    flag: "https://flagcdn.com/sg.svg",
    limitNumber: 8,
    example: "+65 8123 4567",
  },
  {
    name: "Slovakia",
    dialCode: "+421",
    code: "SK",
    flag: "https://flagcdn.com/sk.svg",
    limitNumber: 9,
    example: "+421 911 234 567",
  },
  {
    name: "Slovenia",
    dialCode: "+386",
    code: "SI",
    flag: "https://flagcdn.com/si.svg",
    limitNumber: 9,
    example: "+386 41 234 567",
  },
  {
    name: "South Korea",
    dialCode: "+82",
    code: "KR",
    flag: "https://flagcdn.com/kr.svg",
    limitNumber: 10,
    example: "+82 10 1234 5678",
  },
  {
    name: "Spain",
    dialCode: "+34",
    code: "ES",
    flag: "https://flagcdn.com/es.svg",
    limitNumber: 9,
    example: "+34 612 345 678",
  },
  {
    name: "Sri Lanka",
    dialCode: "+94",
    code: "LK",
    flag: "https://flagcdn.com/lk.svg",
    limitNumber: 9,
    example: "+94 76 123 4567",
  },
  {
    name: "Suriname",
    dialCode: "+597",
    code: "SR",
    flag: "https://flagcdn.com/sr.svg",
    limitNumber: 7,
    example: "+597 123 4567",
  },
  {
    name: "Sweden",
    dialCode: "+46",
    code: "SE",
    flag: "https://flagcdn.com/se.svg",
    limitNumber: 9,
    example: "+46 70 123 45 67",
  },
  {
    name: "Switzerland",
    dialCode: "+41",
    code: "CH",
    flag: "https://flagcdn.com/ch.svg",
    limitNumber: 9,
    example: "+41 79 123 45 67",
  },
  {
    name: "Taiwan",
    dialCode: "+886",
    code: "TW",
    flag: "https://flagcdn.com/tw.svg",
    limitNumber: 9,
    example: "+886 912 345 678",
  },
  {
    name: "Tajikistan",
    dialCode: "+992",
    code: "TJ",
    flag: "https://flagcdn.com/tj.svg",
    limitNumber: 9,
    example: "+992 93 123 4567",
  },
  {
    name: "Thailand",
    dialCode: "+66",
    code: "TH",
    flag: "https://flagcdn.com/th.svg",
    limitNumber: 9,
    example: "+66 81 234 5678",
  },
  {
    name: "Timor-Leste",
    dialCode: "+670",
    code: "TL",
    flag: "https://flagcdn.com/tl.svg",
    limitNumber: 8,
    example: "+670 1234 5678",
  },
  {
    name: "Tonga",
    dialCode: "+676",
    code: "TO",
    flag: "https://flagcdn.com/to.svg",
    limitNumber: 7,
    example: "+676 1234567",
  },
  {
    name: "Trinidad and Tobago",
    dialCode: "+1",
    code: "868",
    flag: "https://flagcdn.com/tt.svg",
    limitNumber: 10,
    example: "+1 868 012 3456",
  },
  {
    name: "Turkey",
    dialCode: "+90",
    code: "TR",
    flag: "https://flagcdn.com/tr.svg",
    limitNumber: 10,
    example: "+90 501 234 5678",
  },
  {
    name: "Turkmenistan",
    dialCode: "+993",
    code: "TM",
    flag: "https://flagcdn.com/tm.svg",
    limitNumber: 8,
    example: "+993 12 345 678",
  },
  {
    name: "Ukraine",
    dialCode: "+380",
    code: "UA",
    flag: "https://flagcdn.com/ua.svg",
    limitNumber: 9,
    example: "+380 67 123 4567",
  },
  {
    name: "United Arab Emirates",
    dialCode: "+971",
    code: "AE",
    flag: "https://flagcdn.com/ae.svg",
    limitNumber: 9,
    example: "+971 50 123 4567",
  },
  {
    name: "United Kingdom",
    dialCode: "+44",
    code: "GB",
    flag: "https://flagcdn.com/gb.svg",
    limitNumber: 10,
    example: "+44 20 7946 0958",
  },
  {
    name: "United States",
    dialCode: "+1",
    code: "US",
    flag: "https://flagcdn.com/us.svg",
    limitNumber: 10,
    example: "+1 (202) 555 0123",
  },
  {
    name: "Uruguay",
    dialCode: "+598",
    code: "UY",
    flag: "https://flagcdn.com/uy.svg",
    limitNumber: 8,
    example: "+598 99 123 456",
  },
  {
    name: "Uzbekistan",
    dialCode: "+998",
    code: "UZ",
    flag: "https://flagcdn.com/uz.svg",
    limitNumber: 9,
    example: "+998 90 123 4567",
  },
  {
    name: "Vanuatu",
    dialCode: "+678",
    code: "VU",
    flag: "https://flagcdn.com/vu.svg",
    limitNumber: 7,
    example: "+678 1234567",
  },
  {
    name: "Venezuela",
    dialCode: "+58",
    code: "VE",
    flag: "https://flagcdn.com/ve.svg",
    limitNumber: 10,
    example: "+58 412 123 4567",
  },
  {
    name: "Vietnam",
    dialCode: "+84",
    code: "VN",
    flag: "https://flagcdn.com/vn.svg",
    limitNumber: 9,
    example: "+84 98 123 4567",
  },
  {
    name: "Yemen",
    dialCode: "+967",
    code: "YE",
    flag: "https://flagcdn.com/ye.svg",
    limitNumber: 9,
    example: "+967 771 234 567",
  },
];
