export const countries = [
  {
    name: "Nigeria",
    dialCode: "+234",
    code: "NG",
    flag: "https://flagcdn.com/ng.svg",
    limitNumber: 10,
    example: "+234 812 345 6789",
  },
  {
    name: "United States",
    dialCode: "+1",
    code: "US",
    flag: "https://flagcdn.com/us.svg",
    limitNumber: 10,
    example: "+1 (202) 555-0123",
  },
  {
    name: "United Kingdom",
    dialCode: "+44",
    code: "GB",
    flag: "https://flagcdn.com/gb.svg",
    limitNumber: 10,
    example: "+44 20 7946 0958",
  },
  {
    name: "Germany",
    dialCode: "+49",
    code: "DE",
    flag: "https://flagcdn.com/de.svg",
    limitNumber: 11,
    example: "+49 176 1234 5678",
  },
  {
    name: "India",
    dialCode: "+91",
    code: "IN",
    flag: "https://flagcdn.com/in.svg",
    limitNumber: 10,
    example: "+91 98765 43210",
  },
  {
    name: "Canada",
    dialCode: "+1",
    code: "CA",
    flag: "https://flagcdn.com/ca.svg",
    limitNumber: 10,
    example: "+1 (416) 555-0123",
  },
  {
    name: "South Africa",
    dialCode: "+27",
    code: "ZA",
    flag: "https://flagcdn.com/za.svg",
    limitNumber: 9,
    example: "+27 83 123 4567",
  },
  {
    name: "Kenya",
    dialCode: "+254",
    code: "KE",
    flag: "https://flagcdn.com/ke.svg",
    limitNumber: 9,
    example: "+254 712 345 678",
  },
  {
    name: "Ghana",
    dialCode: "+233",
    code: "GH",
    flag: "https://flagcdn.com/gh.svg",
    limitNumber: 9,
    example: "+233 24 456 7890",
  },
  {
    name: "France",
    dialCode: "+33",
    code: "FR",
    flag: "https://flagcdn.com/fr.svg",
    limitNumber: 9,
    example: "+33 6 12 34 56 78",
  },
  {
    name: "Brazil",
    dialCode: "+55",
    code: "BR",
    flag: "https://flagcdn.com/br.svg",
    limitNumber: 11,
    example: "+55 11 98765 4321",
  },
  {
    name: "Japan",
    dialCode: "+81",
    code: "JP",
    flag: "https://flagcdn.com/jp.svg",
    limitNumber: 10,
    example: "+81 90 1234 5678",
  },
  {
    name: "Australia",
    dialCode: "+61",
    code: "AU",
    flag: "https://flagcdn.com/au.svg",
    limitNumber: 9,
    example: "+61 412 345 678",
  },
  {
    name: "China",
    dialCode: "+86",
    code: "CN",
    flag: "https://flagcdn.com/cn.svg",
    limitNumber: 11,
    example: "+86 138 1234 5678",
  },
  {
    name: "Russia",
    dialCode: "+7",
    code: "RU",
    flag: "https://flagcdn.com/ru.svg",
    limitNumber: 10,
    example: "+7 912 345 6789",
  },
  {
    name: "Mexico",
    dialCode: "+52",
    code: "MX",
    flag: "https://flagcdn.com/mx.svg",
    limitNumber: 10,
    example: "+52 55 1234 5678",
  },
  {
    name: "Italy",
    dialCode: "+39",
    code: "IT",
    flag: "https://flagcdn.com/it.svg",
    limitNumber: 10,
    example: "+39 345 678 9012",
  },
  {
    name: "Spain",
    dialCode: "+34",
    code: "ES",
    flag: "https://flagcdn.com/es.svg",
    limitNumber: 9,
    example: "+34 612 345 678",
  },
  {
    name: "Turkey",
    dialCode: "+90",
    code: "TR",
    flag: "https://flagcdn.com/tr.svg",
    limitNumber: 10,
    example: "+90 501 234 5678",
  },
  {
    name: "Netherlands",
    dialCode: "+31",
    code: "NL",
    flag: "https://flagcdn.com/nl.svg",
    limitNumber: 9,
    example: "+31 6 12345678",
  },
  {
    name: "Saudi Arabia",
    dialCode: "+966",
    code: "SA",
    flag: "https://flagcdn.com/sa.svg",
    limitNumber: 9,
    example: "+966 50 123 4567",
  },
  {
    name: "United Arab Emirates",
    dialCode: "+971",
    code: "AE",
    flag: "https://flagcdn.com/ae.svg",
    limitNumber: 9,
    example: "+971 50 123 4567",
  },
  {
    name: "Singapore",
    dialCode: "+65",
    code: "SG",
    flag: "https://flagcdn.com/sg.svg",
    limitNumber: 8,
    example: "+65 8123 4567",
  },
  {
    name: "South Korea",
    dialCode: "+82",
    code: "KR",
    flag: "https://flagcdn.com/kr.svg",
    limitNumber: 10,
    example: "+82 10 1234 5678",
  },
  {
    name: "Argentina",
    dialCode: "+54",
    code: "AR",
    flag: "https://flagcdn.com/ar.svg",
    limitNumber: 10,
    example: "+54 11 1234 5678",
  },
  {
    name: "Egypt",
    dialCode: "+20",
    code: "EG",
    flag: "https://flagcdn.com/eg.svg",
    limitNumber: 10,
    example: "+20 100 123 4567",
  },
  {
    name: "Pakistan",
    dialCode: "+92",
    code: "PK",
    flag: "https://flagcdn.com/pk.svg",
    limitNumber: 10,
    example: "+92 300 1234567",
  },
  {
    name: "Indonesia",
    dialCode: "+62",
    code: "ID",
    flag: "https://flagcdn.com/id.svg",
    limitNumber: 10,
    example: "+62 812 3456 7890",
  },
  {
    name: "Philippines",
    dialCode: "+63",
    code: "PH",
    flag: "https://flagcdn.com/ph.svg",
    limitNumber: 10,
    example: "+63 917 123 4567",
  },
  {
    name: "Vietnam",
    dialCode: "+84",
    code: "VN",
    flag: "https://flagcdn.com/vn.svg",
    limitNumber: 9,
    example: "+84 98 123 4567",
  },
  {
    name: "Thailand",
    dialCode: "+66",
    code: "TH",
    flag: "https://flagcdn.com/th.svg",
    limitNumber: 9,
    example: "+66 81 234 5678",
  },
  {
    name: "Malaysia",
    dialCode: "+60",
    code: "MY",
    flag: "https://flagcdn.com/my.svg",
    limitNumber: 9,
    example: "+60 12 345 6789",
  },
  {
    name: "Poland",
    dialCode: "+48",
    code: "PL",
    flag: "https://flagcdn.com/pl.svg",
    limitNumber: 9,
    example: "+48 512 345 678",
  },
  {
    name: "Ukraine",
    dialCode: "+380",
    code: "UA",
    flag: "https://flagcdn.com/ua.svg",
    limitNumber: 9,
    example: "+380 67 123 4567",
  },
  {
    name: "Colombia",
    dialCode: "+57",
    code: "CO",
    flag: "https://flagcdn.com/co.svg",
    limitNumber: 10,
    example: "+57 300 1234567",
  },
  {
    name: "Bangladesh",
    dialCode: "+880",
    code: "BD",
    flag: "https://flagcdn.com/bd.svg",
    limitNumber: 10,
    example: "+880 1812 345678",
  },
];

export const groups = [
  {
    color: "#E6E6E6",
    text: "default",
  },
];
